//test exception 11

int func(int x)
{
	int[] y = alloc_array(int, x);
	return 0;
}

int main()
{
	int x = -1;

	return func(x);
}