//test exception 11

int main() {
  int *foo = NULL;
  return *foo;
}
