//test exception
//Stack overflow via call depth of 2^32

int foo(int x);

int main()
{
	return foo(-1);
}

int foo(int x)
{
	int y; int z;

	if(x==0)
		return 0;

	y = x + 5;
	z = foo(y-6);

	return y + z;
}
