//test exception

int function(int a);
int function2(int a);

int tree(int a, int count) {
    int res = 0;
    if (count != 0) {
        res += a + tree(a, count - 1);
        tree(a, function(count));
        tree(a, function2(count));
    }
    return a + res;
}

int main () {
    int x = 0;
    int y = 0;
    int res = 0;

    res = tree(10, 10);
    return res;
}

int function(int a) {
    a = a % a;
    return a;
}

int function2(int a) {
    return a;
}
