//test exception 8

// This one would give you 14 or 11
int haha (int n) {
  int x = 0;
  while (true) {
    x = x + 1;
  }
  return x;
}

// But this one divides by 0!
int a(int y) {
  int x = y / 0;
  return x;
}

int blah(int one, int two, int three) {
  return one + two * three;
}

int main () {
  int c = 6;
  return blah(a(5), haha(0), c);
}
